"""Add chat history and enhance jobs table

Revision ID: 1390a66e9e46
Revises: 11587c03260b
Create Date: 2025-06-29 18:14:11.633960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1390a66e9e46'
down_revision: Union[str, Sequence[str], None] = '11587c03260b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.add_column('jobs', sa.Column('title', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('prompt', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('gemini_file_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('source_url', sa.String(), nullable=True))
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'source_url')
    op.drop_column('jobs', 'gemini_file_id')
    op.drop_column('jobs', 'prompt')
    op.drop_column('jobs', 'title')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
