"""Add first_name and last_name to User model

Revision ID: 1f3e45323d45
Revises: 5118edbde1ec
Create Date: 2025-07-15 21:32:27.866162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3e45323d45'
down_revision: Union[str, Sequence[str], None] = '5118edbde1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))

    # Update existing rows to set a default value for first_name and last_name
    op.execute(sa.text("UPDATE users SET first_name = '' WHERE first_name IS NULL"))
    op.execute(sa.text("UPDATE users SET last_name = '' WHERE last_name IS NULL"))

    # Alter columns to be non-nullable
    op.alter_column('users', 'first_name',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
