"""add error_message to jobs table

Revision ID: 84dec03bb4fe
Revises: ab181fb5c9e0
Create Date: 2025-06-29 20:58:02.799449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dec03bb4fe'
down_revision: Union[str, Sequence[str], None] = 'ab181fb5c9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'error_message')
    # ### end Alembic commands ###
