"""Add current_agent to jobs table

Revision ID: ab181fb5c9e0
Revises: 1390a66e9e46
Create Date: 2025-06-29 18:46:26.406117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab181fb5c9e0'
down_revision: Union[str, Sequence[str], None] = '1390a66e9e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('current_agent', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'current_agent')
    # ### end Alembic commands ###
