"""Add display_video_url to Job model

Revision ID: ac149b00dbcb
Revises: 1f3e45323d45
Create Date: 2025-07-18 01:26:35.247572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac149b00dbcb'
down_revision: Union[str, Sequence[str], None] = '1f3e45323d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('display_video_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'display_video_url')
    # ### end Alembic commands ###
